apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-gqtw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-gqtw
    app.kubernetes.io/part-of: ci1t-43256-0051-app
  name: devfile-sample-gqtw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-gqtw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-gqtw
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-43256-0051-tenant/ci1t-43256-0051-app/devfile-sample-gqtw@sha256:9e6d59a3add9488ac0a59801d391e08dd1ab965f2132d80826e99dff6e6d6050
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
